import { useState } from 'react'
import {
  Sparkles,
  Database,
  ShieldCheck,
  GitFork,
  Search,
  CheckCircle2,
  XCircle,
  RefreshCw,
  ArrowUpRight,
} from 'lucide-react'
import {
  api,
  type ExtractionProposal,
  type HybridRetrieveResult,
  type ProjectionCheckpoint,
  type ProjectionReconciliation,
} from './api'
import { Badge, Hash } from './App'
import { verifyDomainMerkleProof } from './merkleVerify'

function getTaskTypeStyle(taskType: string) {
  switch (taskType) {
    case 'extract_entities':
      return { color: '#38bdf8', bg: 'rgba(56, 189, 248, 0.12)', border: 'rgba(56, 189, 248, 0.3)' }
    case 'extract_relations':
      return { color: '#c084fc', bg: 'rgba(192, 132, 252, 0.12)', border: 'rgba(192, 132, 252, 0.3)' }
    case 'classify_para':
      return { color: '#4ade80', bg: 'rgba(74, 222, 128, 0.12)', border: 'rgba(74, 222, 128, 0.3)' }
    case 'detect_contradictions':
      return { color: '#fb7185', bg: 'rgba(251, 113, 133, 0.12)', border: 'rgba(251, 113, 133, 0.3)' }
    default:
      return { color: '#93c5fd', bg: 'rgba(147, 197, 253, 0.12)', border: 'rgba(147, 197, 253, 0.3)' }
  }
}

// Generalizes the ParaPanel accept/dismiss pattern (App.tsx) to every extraction_proposals
// task_type (extract_entities, extract_relations, detect_contradictions, ...), not just PARA.
export function ExtractionProposalsPanel({
  proposals,
  status,
  onStatusChange,
  onDecision,
  onSelectMemory,
}: {
  proposals: ExtractionProposal[]
  status: string
  onStatusChange: (status: string) => void
  onDecision: (proposalId: string, decision: 'accept' | 'dismiss') => void
  onSelectMemory: (memoryId: string) => void
}) {
  return (
    <section className="overview-card" style={{ marginBottom: '24px' }}>
      <header className="overview-card-header">
        <div>
          <div className="overview-card-kicker">AUTONOMOUS EXTRACTORS</div>
          <div className="overview-card-title">Extraction Proposals Review</div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <select
            className="session-select form-select"
            value={status}
            onChange={(e) => onStatusChange(e.target.value)}
            style={{ fontSize: '11px', padding: '4px 10px' }}
          >
            <option value="proposed">Proposed</option>
            <option value="accepted">Accepted</option>
            <option value="dismissed">Dismissed</option>
            <option value="stale">Stale</option>
          </select>
          <div className="overview-card-badge">{proposals.length} {status}</div>
        </div>
      </header>
      <div className="overview-card-body">
        <p className="small muted" style={{ margin: '0 0 16px 0' }}>
          Reviewable candidate extractions and classifications generated by autonomous workers. Nothing commits to the primary store without operator confirmation.
        </p>
        {proposals.length === 0 ? (
          <div className="empty-state">
            <h4>No {status} proposals</h4>
            <p>Extraction and contradiction-detection workers produce proposals here once they complete a task.</p>
          </div>
        ) : (
          <div className="item-list" style={{ maxHeight: '540px', overflowY: 'auto', paddingRight: '6px' }}>
            {proposals.map((proposal) => {
              const taskStyle = getTaskTypeStyle(proposal.task_type)
              return (
                <article
                  className="item"
                  key={proposal.id}
                  style={{
                    background: 'rgba(10, 14, 20, 0.65)',
                    border: '1px solid var(--border)',
                    borderRadius: '8px',
                    padding: '14px',
                    marginBottom: '10px',
                  }}
                >
                  <div className="item-head" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <span
                      style={{
                        padding: '2px 8px',
                        borderRadius: '4px',
                        fontSize: '11px',
                        fontWeight: 600,
                        letterSpacing: '0.5px',
                        textTransform: 'uppercase',
                        color: taskStyle.color,
                        background: taskStyle.bg,
                        border: `1px solid ${taskStyle.border}`,
                      }}
                    >
                      {proposal.task_type}
                    </span>
                    <Badge>{proposal.status}</Badge>
                  </div>
                  <pre
                    className="small"
                    style={{
                      whiteSpace: 'pre-wrap',
                      wordBreak: 'break-word',
                      background: 'rgba(0,0,0,0.5)',
                      border: '1px solid var(--border-subtle)',
                      padding: '10px 12px',
                      borderRadius: '6px',
                      fontFamily: 'var(--font-mono, monospace)',
                      fontSize: '11px',
                      lineHeight: '1.4',
                      color: 'var(--text-subtle)',
                    }}
                  >
                    {JSON.stringify(proposal.payload, null, 2)}
                  </pre>
                  {proposal.evidence_quote && (
                    <blockquote
                      style={{
                        margin: '10px 0',
                        padding: '8px 12px',
                        background: 'rgba(56, 189, 248, 0.08)',
                        borderLeft: '3px solid #38bdf8',
                        borderRadius: '0 6px 6px 0',
                        fontSize: '12px',
                        color: 'var(--text)',
                        fontStyle: 'italic',
                      }}
                    >
                      &ldquo;{proposal.evidence_quote}&rdquo;
                    </blockquote>
                  )}
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '10px', flexWrap: 'wrap', gap: '8px' }}>
                    <p className="small muted" style={{ margin: 0 }}>
                      source hash <Hash value={proposal.source_content_hash} />
                    </p>
                    <div className="action-row" style={{ display: 'flex', gap: '8px' }}>
                      <button
                        type="button"
                        className="small-button"
                        onClick={() => onSelectMemory(proposal.source_memory_id)}
                        style={{ display: 'inline-flex', alignItems: 'center', gap: '4px' }}
                      >
                        Inspect source <ArrowUpRight size={12} />
                      </button>
                      {proposal.status === 'proposed' && (
                        <>
                          <button
                            type="button"
                            className="small-button"
                            onClick={() => onDecision(proposal.id, 'accept')}
                            style={{ background: 'rgba(74, 222, 128, 0.15)', color: '#4ade80', borderColor: 'rgba(74, 222, 128, 0.3)' }}
                          >
                            Accept
                          </button>
                          <button
                            type="button"
                            className="small-button"
                            onClick={() => onDecision(proposal.id, 'dismiss')}
                            style={{ background: 'rgba(239, 68, 68, 0.1)', color: '#fca5a5', borderColor: 'rgba(239, 68, 68, 0.3)' }}
                          >
                            Dismiss
                          </button>
                        </>
                      )}
                    </div>
                  </div>
                  {proposal.decision_note && (
                    <p className="small muted" style={{ marginTop: '8px' }}>
                      note: {proposal.decision_note}
                    </p>
                  )}
                </article>
              )
            })}
          </div>
        )}
      </div>
    </section>
  )
}

type ProofState = 'idle' | 'checking' | 'valid' | 'invalid'

// Runs a real hybrid_retrieve query and shows the full trace: per-channel ranks, RRF params,
// candidate pool sizes, graph edges, and a client-side-verified Merkle inclusion proof per
// result -- verification happens in the browser (merkleVerify.ts), not by trusting the server's
// own claim that a result belongs to the trace.
export function RetrievalTraceInspector({ onSelectMemory }: { onSelectMemory: (memoryId: string) => void }) {
  const [query, setQuery] = useState('')
  const [result, setResult] = useState<HybridRetrieveResult | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [proofStates, setProofStates] = useState<Record<number, ProofState>>({})

  const runQuery = async () => {
    if (!query.trim()) return
    setLoading(true)
    setError(null)
    setProofStates({})
    try {
      const response = await api.hybridRetrieve({ query, limit: 10 })
      setResult(response)
    } catch (e) {
      setError(String(e))
    } finally {
      setLoading(false)
    }
  }

  const verifyRank = async (rank: number) => {
    if (!result) return
    setProofStates((prev) => ({ ...prev, [rank]: 'checking' }))
    try {
      const proof = await api.retrievalTraceEvidence(result.trace_id, rank)
      const valid = await verifyDomainMerkleProof(proof)
      setProofStates((prev) => ({ ...prev, [rank]: valid ? 'valid' : 'invalid' }))
    } catch {
      setProofStates((prev) => ({ ...prev, [rank]: 'invalid' }))
    }
  }

  return (
    <section className="overview-card" style={{ marginBottom: '24px' }}>
      <header className="overview-card-header">
        <div>
          <div className="overview-card-kicker">CRYPTOGRAPHIC PROOF</div>
          <div className="overview-card-title">Retrieval Trace Inspector</div>
        </div>
        {result && (
          <Badge>Trace ID: {result.trace_id.slice(0, 10)}…</Badge>
        )}
      </header>
      <div className="overview-card-body">
        <p className="small muted" style={{ margin: '0 0 16px 0' }}>
          Every query persists a full, independently verifiable execution trace. Click &ldquo;Verify inclusion proof&rdquo; to compute the Merkle root directly in this browser and verify that the retrieved item was cryptographically bound to the query execution.
        </p>
        <form
          className="tab-search-hero"
          style={{ marginBottom: '16px' }}
          onSubmit={(e) => {
            e.preventDefault()
            runQuery()
          }}
        >
          <Search size={16} className="search-icon" style={{ opacity: 0.6 }} />
          <input
            className="search-input"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search query text, a memory ID, or a sha256: content hash to inspect trace..."
          />
          <button className="small-button" type="submit" disabled={loading} style={{ padding: '6px 16px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            {loading ? <RefreshCw size={13} className="spin-slow" /> : <Search size={13} />}
            {loading ? 'Searching…' : 'Inspect Trace'}
          </button>
        </form>
        {error && <p className="error-text">{error}</p>}
        {result && (
          <>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px', margin: '14px 0', flexWrap: 'wrap' }}>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                {Object.entries(result.channel_status).map(([channel, status]) => (
                  <Badge key={channel}>{channel}: {status}</Badge>
                ))}
              </div>
              <Badge>root <Hash value={result.root_hash} /></Badge>
            </div>
            {result.degraded.length > 0 && (
              <p className="small muted">{result.degraded.length} result(s) dropped by diversity/budget controls.</p>
            )}
            <div className="item-list" style={{ maxHeight: '520px', overflowY: 'auto', paddingRight: '6px' }}>
              {result.results.map((memory, i) => {
                const rank = i + 1
                const proofState = proofStates[rank] ?? 'idle'
                return (
                  <article className="item" key={memory.id} style={{ background: 'rgba(10, 14, 20, 0.65)', border: '1px solid var(--border)', borderRadius: '8px', padding: '14px', marginBottom: '10px' }}>
                    <div className="item-head" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <strong style={{ color: 'var(--accent)', fontSize: '13px' }}>Rank #{rank}</strong>
                        <Badge>{memory.evidence_class}</Badge>
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                        {proofState === 'valid' && (
                          <span style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', fontSize: '11px', color: '#4ade80', fontWeight: 600 }}>
                            <CheckCircle2 size={13} /> Merkle verified
                          </span>
                        )}
                        {proofState === 'invalid' && (
                          <span style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', fontSize: '11px', color: '#fb7185', fontWeight: 600 }}>
                            <XCircle size={13} /> Verification failed
                          </span>
                        )}
                      </div>
                    </div>
                    <p className="small" style={{ margin: '6px 0', lineHeight: '1.45' }}>{memory.content.slice(0, 240)}</p>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '10px', flexWrap: 'wrap', gap: '8px' }}>
                      <p className="small muted" style={{ margin: 0 }}>content hash <Hash value={memory.content_hash} /></p>
                      <div className="action-row" style={{ display: 'flex', gap: '8px' }}>
                        <button type="button" className="small-button" onClick={() => onSelectMemory(memory.id)}>Inspect memory</button>
                        <button
                          type="button"
                          className="small-button"
                          disabled={proofState === 'checking'}
                          onClick={() => verifyRank(rank)}
                          style={proofState === 'valid' ? { borderColor: '#4ade80', color: '#4ade80' } : {}}
                        >
                          {proofState === 'checking' ? 'Verifying…' : proofState === 'valid' ? 'Re-verify Proof' : 'Verify inclusion proof'}
                        </button>
                      </div>
                    </div>
                  </article>
                )
              })}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

// Projection checkpoint/reconciliation status -- recompute from canonical SQLite, compare
// against the last stored checkpoint, and show whether a projection is degraded, not just
// assert it's fine.
export function ProjectionHealthPanel() {
  const [projectionId, setProjectionId] = useState('memories')
  const [checkpoints, setCheckpoints] = useState<ProjectionCheckpoint[]>([])
  const [reconciliation, setReconciliation] = useState<ProjectionReconciliation | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)

  const refresh = async (id: string) => {
    try {
      const history = await api.projectionCheckpoints(id)
      setCheckpoints(history)
      setError(null)
    } catch (e) {
      setError(String(e))
    }
  }

  const runAction = async (action: 'checkpoint' | 'reconcile' | 'rebuild') => {
    setBusy(true)
    setError(null)
    try {
      if (action === 'checkpoint') await api.createProjectionCheckpoint(projectionId)
      if (action === 'rebuild') await api.rebuildProjectionCheckpoint(projectionId)
      if (action === 'reconcile') setReconciliation(await api.reconcileProjectionCheckpoint(projectionId))
      await refresh(projectionId)
    } catch (e) {
      setError(String(e))
    } finally {
      setBusy(false)
    }
  }

  return (
    <section className="overview-card">
      <header className="overview-card-header">
        <div>
          <div className="overview-card-kicker">DRIFT DETECTION</div>
          <div className="overview-card-title">Projection Health &amp; Checkpoints</div>
        </div>
        <select
          className="session-select form-select"
          value={projectionId}
          onChange={(e) => {
            setProjectionId(e.target.value)
            refresh(e.target.value)
          }}
          style={{ fontSize: '11px', padding: '4px 10px' }}
        >
          <option value="memories">memories</option>
          <option value="entities">entities</option>
          <option value="relations">relations</option>
        </select>
      </header>
      <div className="overview-card-body">
        <p className="small muted" style={{ margin: '0 0 14px 0' }}>
          Checkpoints recompute from canonical SQLite — state drift is flagged explicitly, not silently served.
        </p>
        <div className="action-row" style={{ marginBottom: '16px', display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <button type="button" className="small-button" disabled={busy} onClick={() => runAction('checkpoint')}>
            Create checkpoint
          </button>
          <button type="button" className="small-button" disabled={busy} onClick={() => runAction('reconcile')}>
            Reconcile
          </button>
          <button type="button" className="small-button" disabled={busy} onClick={() => runAction('rebuild')}>
            Rebuild &amp; verify
          </button>
          <button type="button" className="small-button" disabled={busy} onClick={() => refresh(projectionId)}>
            Refresh
          </button>
        </div>
        {error && <p className="error-text">{error}</p>}
        {reconciliation && (
          <div className="item" style={{ marginBottom: '14px', background: 'rgba(10, 14, 20, 0.65)', border: '1px solid var(--border)', borderRadius: '8px', padding: '12px' }}>
            <div className="item-head" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
              <strong>Last reconciliation</strong>
              <Badge>{reconciliation.equal ? 'equal' : reconciliation.action}</Badge>
            </div>
            {!reconciliation.equal && (
              <p className="small muted" style={{ margin: 0 }}>
                missing: {reconciliation.missing.length}, extra: {reconciliation.extra.length}, reordered: {String(reconciliation.reordered)}
              </p>
            )}
          </div>
        )}
        {checkpoints.length === 0 ? (
          <div className="empty-state">
            <h4>No checkpoints yet</h4>
            <p>Create one to establish a baseline for this projection.</p>
          </div>
        ) : (
          <div className="item-list" style={{ maxHeight: '360px', overflowY: 'auto', paddingRight: '6px' }}>
            {checkpoints.map((checkpoint) => (
              <article className="item" key={checkpoint.id} style={{ background: 'rgba(10, 14, 20, 0.65)', border: '1px solid var(--border)', borderRadius: '8px', padding: '12px', marginBottom: '8px' }}>
                <div className="item-head" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                  <strong style={{ color: 'var(--accent)' }}>{checkpoint.leaf_count} leaves</strong>
                  <Badge>{checkpoint.status}</Badge>
                </div>
                <p className="small muted" style={{ margin: '4px 0' }}>root <Hash value={checkpoint.root_hash} /></p>
                <p className="small muted" style={{ margin: 0 }}>{checkpoint.created_at}</p>
              </article>
            ))}
          </div>
        )}
      </div>
    </section>
  )
}

export function ProvenanceTab({
  proposals,
  status,
  onStatusChange,
  onDecision,
  onSelectMemory,
}: {
  proposals: ExtractionProposal[]
  status: string
  onStatusChange: (status: string) => void
  onDecision: (proposalId: string, decision: 'accept' | 'dismiss') => void
  onSelectMemory: (memoryId: string) => void
}) {
  return (
    <div className="tab-panel provenance-tab">
      <div className="overview-header" style={{ marginBottom: '20px' }}>
        <div>
          <div className="overview-kicker">AUTONOMOUS LINEAGE &amp; TRACEABILITY</div>
          <h2 className="overview-title">Provenance &amp; Cryptographic Traces</h2>
          <p className="overview-subtitle">
            Review autonomous extraction proposals, audit hybrid retrieval Merkle inclusion proofs, and monitor projection checkpoint drift against canonical SQLite.
          </p>
        </div>
      </div>

      <div className="overview-kpi-grid" style={{ marginBottom: '24px' }}>
        <div className="kpi-card">
          <div className="kpi-icon-wrap memories">
            <Sparkles size={20} />
          </div>
          <div className="kpi-content">
            <div className="kpi-value">{proposals.length}</div>
            <div className="kpi-label">Proposals ({status})</div>
            <div className="kpi-subtext">Autonomous workers</div>
          </div>
        </div>

        <div className="kpi-card">
          <div className="kpi-icon-wrap relations">
            <Database size={20} />
          </div>
          <div className="kpi-content">
            <div className="kpi-value">memories</div>
            <div className="kpi-label">Target Projection</div>
            <div className="kpi-subtext">Checkpoints active</div>
          </div>
        </div>

        <div className="kpi-card">
          <div className="kpi-icon-wrap readiness">
            <ShieldCheck size={20} />
          </div>
          <div className="kpi-content">
            <div className="kpi-value">Client Merkle</div>
            <div className="kpi-label">Inclusion Verifier</div>
            <div className="kpi-subtext">Browser cryptography</div>
          </div>
        </div>

        <div className="kpi-card">
          <div className="kpi-icon-wrap sessions">
            <GitFork size={20} />
          </div>
          <div className="kpi-content">
            <div className="kpi-value">Canonical DAG</div>
            <div className="kpi-label">Store Lineage</div>
            <div className="kpi-subtext">Drift detection active</div>
          </div>
        </div>
      </div>

      <ExtractionProposalsPanel
        proposals={proposals}
        status={status}
        onStatusChange={onStatusChange}
        onDecision={onDecision}
        onSelectMemory={onSelectMemory}
      />

      <RetrievalTraceInspector onSelectMemory={onSelectMemory} />

      <ProjectionHealthPanel />
    </div>
  )
}
