"""Build every Claude Design board from the captured console, extend canvas.json, and write DESIGN.md.

Inputs : boards-src/<capture>.json (captured or generated by planned.py), the round-1 boards in cortex-canvas/
Outputs: canvas-publish/project/*.dc.html + canvas.json, and viewer/DESIGN.md in the repo.
The board table below is the single source of truth for both the canvas and DESIGN.md.
"""
import json, re, html as htmllib
from html.parser import HTMLParser
from pathlib import Path

import os
S = Path(os.environ.get('DESIGN_WORK', '.')).resolve()  # the working folder: boards-src/, canvas-live/, canvas-publish/ ...
HERE = Path(__file__).resolve().parent
SRC = HERE.parent / 'src' / 'console'
REPO_DESIGN = HERE.parent / 'DESIGN.md'
OUT = S / 'canvas-publish' / 'project'
OUT.mkdir(parents=True, exist_ok=True)
for old in OUT.glob('*'):
    old.unlink()
MARK = '/_blob/449ef5c64249b8da2af8aa6ab6de11ae'
MEASURED = json.loads((S / 'measured.json').read_text()) if (S / 'measured.json').exists() else {}

# capture name -> uploaded graph raster (the Graph lens is a <canvas>; it cannot be serialized)
CANVAS_IMAGES = json.loads((S / 'canvas-images.json').read_text()) if (S / 'canvas-images.json').exists() else {}

# (stem, capture, canvas title, status, where it lives in the code, notes)
B = {}
def board(stem, cap, title, status, source, note=''):
    # a page is a drawer over the lens now; say so in its name so nobody looks for a page
    if 'pages/' in source and status == 'built' and not title.startswith('Phone') and not title.startswith('Tablet') and 'drawer' not in title.lower():
        title += ' · drawer'
    B[stem] = dict(stem=stem, cap=cap, title=title, status=status, source=source, note=note)

# --- built ---
board('Graph3DOverview', 'graph-3d-overview', 'Graph lens, 3D — nothing selected: the inspector shows the workspace', 'built', 'GraphLens.tsx, Graph3D.tsx, Inspector.tsx (WorkspaceSummary)', 'Default view. 3D is the default; the lattice is faint; every cube owns one cell.')
board('Graph3DEdge', 'graph-3d-edge', 'Graph lens, 3D — an edge selected', 'built', 'Graph3D.tsx (pickEdge), Inspector.tsx (EdgeInspector)', 'Click a line (within 6px). The edge lights, its two ends stay lit, the rest recede; the inspector says what kind of edge it is and links both ends.')
board('Graph3DPinned', 'graph-3d-pinned', 'Graph lens, 3D — a dragged cube is pinned', 'built', 'Graph3D.tsx (drag, setPinned)', 'Drag moves a cube on the plane facing the camera; it lands in the nearest free cell and stays pinned (outlined). Double-click unpins one; “Unpin n” in the bar unpins all. Pins are view-only; nothing is written.')
board('Graph3DNoSnap', 'graph-3d-nosnap', 'Graph lens, 3D — Snap to grid off', 'built', 'GraphLens.tsx, Graph3D.tsx (setSnap), settings.ts', 'Nodes sit where the force layout leaves them; the faint grid stays as a frame of reference.')
board('Graph3DLegend', 'graph-3d-legend', 'Graph lens, 3D — legend open', 'built', 'GraphLens.tsx (LegendRow)', 'The legend starts closed so it never covers the graph. Each row is also a switch for the same facet the rail has.')
board('Graph3DHidden', 'graph-3d-hidden', 'Graph lens — the selection is hidden by a filter', 'built', 'model.ts (selectionHidden), GraphLens.tsx', 'The inspector still shows the item; the lens says it is not drawn and offers Reset facets.')
board('Graph3DFar', 'graph-3d-far', 'Graph lens, 3D — zoomed far out', 'built', 'Graph3D.tsx (applyScreenFloor, latticeStride), gridSnap.ts', 'Cubes keep a 5px floor, arrowheads and the selected edge keep a minimum size, labels that would overlap are dropped, the grid coarsens by powers of two, and pulling back stops at 2.5x the framing distance.')
board('Graph3DNear', 'graph-3d-near', 'Graph lens, 3D — zoomed in close', 'built', 'Graph3D.tsx', 'Zoom goes toward the pointer and stops at 16 units, so the camera never enters the cloud. Keyboard: arrows orbit, shift+arrows pan, + and − zoom, F frames everything, Esc clears.')
board('Graph2D', 'graph-2d', 'Graph lens, 2D — a toggle from 3D', 'built', 'GraphLens.tsx', 'Squares on a faint square grid, snapped to cells; same facets, selection and inspector.')
board('Graph2DNoSnap', 'graph-2d-nosnap', 'Graph lens, 2D — Snap to grid off', 'built', 'GraphLens.tsx (snapNodes)')
board('GraphFacets', 'graph-facets', 'Facet rail — memory source, edge types and predicates', 'built', 'FacetRail.tsx, model.ts', 'Finer switches sit under the edge group they refine; the similarity cut-off runs 0.20–0.99.')
board('GraphNoWebgl', 'graph-nowebgl', 'Graph lens — no WebGL, so 2D, and it says so', 'built', 'GraphLens.tsx (no3d)', 'The 3D choice is kept; the notice explains why 2D is showing.')
board('PhoneGraph2D', 'phone-graph-2d', 'Phone — Graph in 2D', 'built', 'Phone.tsx, GraphLens.tsx')
board('GraphPrimary', 'graph-primary', 'Graph lens — the whole profile (read-only)', 'built', 'GraphLens.tsx, FacetRail.tsx, Inspector.tsx', 'Scope: Primary profile. Writes are hidden and the footer says why.')
board('TimelinePrimary', 'timeline-primary', 'Timeline lens — the same selection, placed in time', 'built', 'TimelineLens.tsx, model.ts', 'A memory is placed at its event time, else when the store recorded it; no-session memories are their own lane.')
board('TimelineWindow', 'timeline-window', 'Timeline lens — windowed to 7 days', 'built', 'ChainRail.tsx, state.tsx', 'The window is shared with the Graph lens.')
board('RailGraph', 'rail-graph', 'Graph lens — a writable agent workspace', 'built', 'MemoryActions.tsx', 'Write actions appear only in a verified, writable workspace.')
board('RailTimeline', 'rail-timeline', 'Collapsed rail — Timeline lens', 'built', 'Shell.tsx (Rail), settings.ts', 'Rail collapses to icons; also automatic on narrow windows.')
board('TopbarGraph', 'topbar-graph', 'Top bar — Graph lens', 'built', 'Shell.tsx (TopBar)', 'Shield’s form of navigation, chosen in Settings → Layout.')
board('TopbarTimeline', 'topbar-timeline', 'Top bar — Timeline lens', 'built', 'Shell.tsx (TopBar)')
board('TopbarSessions', 'topbar-sessions', 'Top bar — Sessions page', 'built', 'pages/SessionsPage.tsx')
board('SignIn', 'signin', 'Sign in — matches Shield', 'built', 'SignIn.tsx')
board('SignInCreate', 'signin-create', 'Sign in — create account', 'built', 'SignIn.tsx')
board('RecallHybrid', 'recall-hybrid', 'Recall — Hybrid, with per-channel ranks', 'built', 'Recall.tsx')
board('RecallContext', 'recall-context', 'Recall — Context block', 'built', 'Recall.tsx, contextBlock.ts', 'POST /api/context/assemble')
board('ReviewDrawer', 'review', 'Review — what the workers proposed', 'built', 'Review.tsx, reviewData.ts')
board('ReviewConfirm', 'review-confirm', 'Review — accepting says what it will write first', 'built', 'Review.tsx')
board('InspectorVerify', 'inspector-verify', 'Inspector — server verifies a memory’s history', 'built', 'Inspector.tsx, VerifyPanel.tsx, verify.ts', 'GET /api/memory/{id}/verify-chain')
board('InspectorExtract', 'inspector-extract', 'Inspector — request extraction', 'built', 'MemoryActions.tsx, actions.ts', 'POST /api/inference/tasks, POST /api/memory/{id}/extract-structural')
board('InspectorSupersede', 'inspector-supersede', 'Inspector — supersede', 'built', 'MemoryActions.tsx')
board('InspectorForget', 'inspector-forget', 'Inspector — forget (two steps)', 'built', 'MemoryActions.tsx')
board('InspectorFiles', 'inspector-files', 'Inspector — files, with download', 'built', 'Inspector.tsx (FilesTab), download.ts')
board('IntegrityServer', 'integrity', 'Integrity — server and browser verification', 'built', 'Integrity.tsx, integrity.ts, merkleVerify.ts', 'GET /api/session/{id}/verify-chain beside the browser-recomputed proofs.')
board('IntegrityCheckpoints', 'integrity-checkpoints', 'Integrity — checkpoints', 'built', 'Integrity.tsx')
board('IntegrityLinks', 'integrity-links', 'Integrity — links', 'built', 'Integrity.tsx')
board('Memories', 'memories', 'Memories', 'built', 'pages/MemoriesPage.tsx')
board('MemoriesEmpty', 'memories-empty', 'Memories — nothing matches', 'built', 'pages/MemoriesPage.tsx')
board('Entities', 'entities', 'Entities — lookup and path', 'built', 'pages/EntitiesPage.tsx, entities.ts')
board('Sessions', 'sessions', 'Sessions', 'built', 'pages/SessionsPage.tsx, sessions.ts')
board('Agents', 'agents', 'Agents — identity and devices', 'built', 'pages/AgentsPage.tsx, agents.ts')
board('Operations', 'operations', 'Operations', 'built', 'pages/OperationsPage.tsx, ops.ts')
board('SettingsLayout', 'settings-layout', 'Settings — Layout (rail or top bar)', 'built', 'pages/SettingsPage.tsx, settings.ts')
board('SettingsInference', 'settings-inference', 'Settings — Inference policy', 'built', 'pages/settings/InferenceSection.tsx, inferenceForm.ts')
board('SettingsEmbeddings', 'settings-embeddings', 'Settings — Embeddings', 'built', 'pages/settings/EmbeddingsSection.tsx')
board('SettingsAccount', 'settings-account', 'Settings — Account (a token has no account)', 'built', 'pages/settings/AccountSection.tsx, account.ts')
board('SettingsDeveloper', 'settings-developer', 'Settings — Developer (an honest self-test failure)', 'built', 'pages/settings/DeveloperSection.tsx')
board('Unavailable', 'unavailable', 'State — the API is unreachable', 'built', 'state.tsx, Shell.tsx')
board('PhoneGraphPrimary', 'phone-graph-primary', 'Phone — Graph', 'built', 'Phone.tsx')
board('PhoneTimeline', 'phone-timeline', 'Phone — Timeline', 'built', 'Phone.tsx, TimelineLens.tsx')
board('PhoneFilters', 'phone-filters', 'Phone — Filters sheet', 'built', 'Phone.tsx, FacetRail.tsx')
board('PhoneTime', 'phone-time', 'Phone — Time sheet', 'built', 'Phone.tsx, ChainRail.tsx')
board('PhoneMore', 'phone-more', 'Phone — More sheet', 'built', 'Phone.tsx, nav.ts')
board('PhoneInspector', 'phone-inspector', 'Phone — inspector sheet', 'built', 'Phone.tsx, Inspector.tsx')
board('PhoneMemories', 'phone-memories', 'Phone — Memories as cards', 'built', 'pages/MemoriesPage.tsx, console.css')
board('PhoneSessions', 'phone-sessions', 'Phone — Sessions list, then detail', 'built', 'pages/SessionsPage.tsx', 'Choosing a session opens it; “All sessions” returns.')
board('PhoneEntities', 'phone-entities', 'Phone — Entities', 'built', 'pages/EntitiesPage.tsx')
board('PhoneOperations', 'phone-operations', 'Phone — Operations', 'built', 'pages/OperationsPage.tsx')
board('PhoneAgents', 'phone-agents', 'Phone — Agents', 'built', 'pages/AgentsPage.tsx')
board('PhoneSettings', 'phone-settings', 'Phone — Settings', 'built', 'pages/SettingsPage.tsx')

board('InspectorProvenance', 'inspector-provenance', 'Inspector — provenance: who said it, from where, and the export', 'built', 'Inspector.tsx (ProvenanceTab), VerifyPanel.tsx', 'GET /api/memory/{id}/provenance; the export is the server’s own document.')
board('InspectorNeighbors', 'inspector-neighbors', 'Inspector — neighbours in the graph', 'built', 'Inspector.tsx (NeighborsTab)')
board('InspectorContradictions', 'inspector-contradictions', 'Inspector — contradictions, and the actions that resolve them', 'built', 'Inspector.tsx, MemoryActions.tsx')
board('InspectorTelemetry', 'inspector-telemetry', 'Inspector — telemetry attached to the memory', 'built', 'Inspector.tsx (TelemetryTab)')
board('MemoriesNew', 'memories-new', 'Memories — writing a memory (agent workspace only)', 'built', 'pages/MemoriesPage.tsx (NewMemory)', 'Only a verified writable workspace sees New memory; it says whose memory it will be.')
board('EntitiesPath', 'entities-path', 'Entities — a path between two entities', 'built', 'pages/EntitiesPage.tsx, entities.ts', 'Each hop names the relation that connects it.')
board('SessionsReplay', 'sessions-replay', 'Sessions — replay, with its completeness stated', 'built', 'pages/SessionsPage.tsx', 'Replay says what it cannot prove: it does not execute tools.')
board('SessionsTelemetry', 'sessions-telemetry', 'Sessions — telemetry summary', 'built', 'pages/SessionsPage.tsx')
board('SessionsInvocations', 'sessions-invocations', 'Sessions — invocation correlations', 'built', 'pages/SessionsPage.tsx')
board('SettingsLayoutTop', 'settings-layout-top', 'Settings — Top bar chosen (and Snap to grid)', 'built', 'pages/SettingsPage.tsx, settings.ts')
board('GraphEmpty', 'graph-empty', 'Graph lens — a workspace with no memories yet', 'built', 'GraphLens.tsx', 'The inspector still shows the workspace; the lens says why it is empty.')
board('TimelineEmpty', 'timeline-empty', 'Timeline lens — nothing to place', 'built', 'TimelineLens.tsx')
board('RecallEmpty', 'recall-empty', 'Recall — no results', 'built', 'Recall.tsx', 'Says what was searched and what to try, without implying a failure.')
board('TabletGraph', 'tablet-graph', 'Tablet (1024) — Graph', 'built', 'console.css (max-width: 1180px)', 'The facet rail becomes a strip above the lens; the rail shell collapses to icons.')
board('TabletTimeline', 'tablet-timeline', 'Tablet (1024) — Timeline', 'built', 'console.css (max-width: 1180px)')
board('TabletMemories', 'tablet-memories', 'Tablet (1024) — Memories', 'built', 'pages/MemoriesPage.tsx')
board('TabletSettings', 'tablet-settings', 'Tablet (820) — Settings', 'built', 'pages/SettingsPage.tsx')
board('PhoneSignIn', 'phone-signin', 'Phone — Sign in', 'built', 'SignIn.tsx')
board('PhoneRecall', 'phone-recall', 'Phone — Recall: query on its own row, modes beneath', 'built', 'Recall.tsx, console.css')
board('PhoneReview', 'phone-review', 'Phone — Review', 'built', 'Review.tsx')
board('PhoneGraphLegend', 'phone-graph-legend', 'Phone — Graph with the legend open', 'built', 'GraphLens.tsx')

board('DrawerTimelineSessions', 'drawer-timeline-sessions', 'Sessions drawer over the Timeline lens', 'built', 'PageDrawer.tsx, pages/SessionsPage.tsx', 'The route keeps the lens: #timeline/sessions. Closing returns to the timeline exactly as it was.')
board('DrawerSessionFromLens', 'drawer-session-from-lens', 'A session in the lens opens its own drawer', 'built', 'Inspector.tsx (SessionInspector), state.tsx (openPage)', '“Exchanges, replay, telemetry” on a selected session opens the Sessions drawer aimed at that session.')
board('DrawerEntityFromGraph', 'drawer-entity-from-graph', 'An entity in the graph opens neighbours and paths', 'built', 'Inspector.tsx (EntityInspector), pages/EntitiesPage.tsx', '“Neighbours and paths” opens the Entities drawer with that entity already looked up.')

board('InspectorLink', 'inspector-link', 'Inspector — link a memory to an entity', 'built', 'MemoryActions.tsx (link)', 'POST /api/memory/link-entities; says what it will write before it writes it.')
board('InspectorContradict', 'inspector-contradict', 'Inspector — mark two memories as contradicting', 'built', 'MemoryActions.tsx (contradiction)', 'POST /api/memory/contradictions; the edge appears on the graph as a dashed line.')
board('ReviewPara', 'review-para', 'Review — PARA classifications', 'built', 'Review.tsx (PARA)', 'POST /api/para/classifications/{id}/decision')
board('ReviewTasks', 'review-tasks', 'Review — inference tasks by status', 'built', 'Review.tsx (Tasks)', 'Read-only: workers claim and complete tasks; the console only shows them.')
board('ReviewReadonly', 'review-readonly', 'Review — a read-only workspace', 'built', 'Review.tsx', 'The queue can be inspected, not decided on; the drawer says why.')
board('SessionsMemories', 'sessions-memories', 'Sessions — the memories a session wrote', 'built', 'pages/SessionsPage.tsx', 'GET /api/session/{id}/memories')
board('SessionsTrace', 'sessions-trace', 'Sessions — decision trace lookup', 'built', 'pages/SessionsPage.tsx', 'GET /api/session/{id}/decision-trace; the trace id comes from the runtime that made the decision.')
board('SessionsKernel', 'sessions-kernel', 'Sessions — kernel intents', 'built', 'pages/SessionsPage.tsx', 'GET /api/session/{id}/kernel-intents')
board('AgentsPair', 'agents-pair', 'Agents — pair a device', 'built', 'pages/AgentsPage.tsx (PairForm)', 'POST /api/agent-devices/associate')
board('AgentsPaired', 'agents-paired', 'Agents — a paired device, with rename, detach and revoke', 'built', 'pages/AgentsPage.tsx', 'Revoke is the danger-quiet button; detach keeps the pairing record.')
board('SettingsAccountSignedIn', 'settings-account-signed-in', 'Settings — Account, signed in as an account', 'built', 'pages/settings/AccountSection.tsx', 'ILLUSTRATIVE DATA: the dev fixture signs in by token, which has no account, so /api/auth/me, /sessions and /events were stubbed with the real response shapes (accounts.py).')
board('SignInError', 'signin-error', 'Sign in — wrong email or password', 'built', 'SignIn.tsx', 'The server’s own message, shown as returned. The response is stubbed: the fixture has no account to fail against.')
board('SignInPending', 'signin-pending', 'Sign in — an account waiting for approval', 'built', 'SignIn.tsx', 'accounts.py: “account requires email verification or administrator approval”. Stubbed response.')
board('SignInExpired', 'signin-expired', 'Sign in — session expired', 'built', 'ConsoleApp.tsx, SignIn.tsx', 'Any 401 returns here with this notice.')
board('IntegrityCheckpointNew', 'integrity-checkpoint-new', 'Integrity — a new checkpoint, then reconcile', 'built', 'Integrity.tsx', 'POST /api/projections/{id}/checkpoint and /reconcile.')
board('IntegrityConfirmRebuild', 'integrity-confirm-rebuild', 'Integrity — rebuild asks first', 'built', 'Integrity.tsx', 'Rebuild recomputes the projection for the whole store; it is confirmed and named.')
board('OperationsReadiness', 'operations-readiness', 'Operations — the full readiness check', 'built', 'pages/OperationsPage.tsx', 'GET /readyz; slower than the snapshot, so it is a button.')
board('RecallLexical', 'recall-lexical', 'Recall — lexical results', 'built', 'Recall.tsx', 'Plain text search; no trace is kept.')
board('RecallError', 'recall-error', 'Recall — the server refused', 'built', 'Recall.tsx', 'The server’s message, in a conflict callout. Stubbed response.')
board('TimelineSessionSelected', 'timeline-session-selected', 'Timeline — a session selected', 'built', 'TimelineLens.tsx, Inspector.tsx (SessionInspector)', 'The base for the runtime and end-session designs.')

# --- planned: designed, not built ---
board('PlannedRuntimeTimeline', 'planned-runtime-timeline', 'PLANNED — the agent runtime on the timeline', 'planned', 'TimelineLens.tsx, Inspector.tsx (SessionInspector)', 'Needs GET /api/session/{id}/runtime; the controller lives in the MCP process. Deny and ask decisions become marks on the lane.')
board('PlannedRuntimes', 'planned-runtimes', 'PLANNED — Operations: agent runtimes', 'planned', 'pages/OperationsPage.tsx', 'Needs GET /api/runtimes. A row leads back to the Timeline, windowed to that runtime.')
board('PlannedWorkers', 'planned-workers', 'PLANNED — Operations: workers', 'planned', 'pages/OperationsPage.tsx', 'Needs GET /api/workers and a heartbeat each worker writes. “Not seen” is not “idle”.')
board('PlannedConnectors', 'planned-connectors', 'PLANNED — Operations: connectors and ingest', 'planned', 'pages/OperationsPage.tsx', 'Needs GET /api/connectors. Each row leads back to the Graph or Timeline with the Memory source facet set.')
board('PlannedTokens', 'planned-tokens', 'PLANNED — Settings: API tokens', 'planned', 'pages/settings/AccountSection.tsx', 'Needs GET/POST /api/auth/tokens and /revoke. Shown once; the server keeps a hash.')
board('PlannedProfile', 'planned-profile', 'PLANNED — Settings: Profile (read-only)', 'planned', 'pages/SettingsPage.tsx', 'Needs GET /api/profile/config, redacted. Read-only on purpose: configuration is set in config.yaml or the environment.')
board('PlannedExportWindow', 'planned-export-window', 'PLANNED — export what the timeline is showing', 'planned', 'ChainRail.tsx', 'Needs POST /api/provenance/export taking the window and facets.')
board('PlannedEndSession', 'planned-end-session', 'PLANNED — end a session', 'planned', 'pages/SessionsPage.tsx', 'Needs POST /api/session/{id}/end. Starting a session stays implicit.')
board('PlannedImport', 'planned-import', 'PLANNED — import a document or transcript', 'planned', 'pages/MemoriesPage.tsx', 'Needs POST /api/import (multipart). Imports arrive as memories with proposals in Review; nothing reaches the graph undecided.')
board('PlannedResetRequest', 'planned-reset-request', 'PLANNED — Forgot password', 'planned', 'SignIn.tsx (new mode)', 'Needs UI only: POST /api/auth/password-reset/request exists. Unavailable delivery is the 503 state.')
board('PlannedResetConfirm', 'planned-reset-confirm', 'PLANNED — Choose a new password', 'planned', 'SignIn.tsx (new mode)', 'Needs UI only: POST /api/auth/password-reset/confirm exists (400 on an invalid or expired code).')
board('PlannedApprovals', 'planned-approvals', 'PLANNED — Accounts waiting for approval', 'planned', 'pages/settings/AccountSection.tsx', 'Needs GET /api/auth/admin/pending (new). POST /api/auth/admin/approve exists.')
board('PlannedVault', 'planned-vault', 'PLANNED — Trust vault lookup', 'planned', 'pages/settings/DeveloperSection.tsx', 'Needs GET /api/vault/leaf?leaf_hash= (new); the vault directory is server configuration.')
board('PlannedAttach', 'planned-attach', 'PLANNED — Attach a file', 'planned', 'Inspector.tsx (FilesTab)', 'Needs POST /api/memory/{id}/attachments (new, upload); 200 MB cap; content-addressed.')
board('PlannedLinkVerify', 'planned-link-verify', 'PLANNED — Verify an integrity link', 'planned', 'Integrity.tsx (Links tab)', 'Needs POST /api/memory/{id}/verify-link (new); DAG location is server configuration.')
board('PlannedAnchor', 'planned-anchor', 'PLANNED — Anchor a session root', 'planned', 'Integrity.tsx (Sessions tab)', 'Needs POST /api/session/{id}/anchor (new). Outward-facing: confirmed, named, irreversible.')
board('PlannedBackup', 'planned-backup', 'PLANNED — Backup and check', 'planned', 'pages/OperationsPage.tsx', 'Needs POST /api/backup and /api/backup/reconcile (new); destination is server configuration.')

ROWS = [
    ('The Graph lens: 3D by default, on a faint lattice; select a node or a line', ['Graph3DOverview', 'Graph3DEdge']),
    ('Drag to pin a cube; Snap to grid off; the legend', ['Graph3DPinned', 'Graph3DNoSnap']),
    ('A filter can hide the selection; the legend is also a set of switches', ['Graph3DLegend', 'Graph3DHidden']),
    ('Every level of resolution: the graph and the grid stay intact', ['Graph3DFar', 'Graph3DNear']),
    ('2D is a toggle: the same graph on a square grid', ['Graph2D', 'Graph2DNoSnap']),
    ('The facet rail, and what happens without WebGL', ['GraphFacets', 'GraphNoWebgl']),
    ('Two lenses, one selection: the whole profile, read-only', ['GraphPrimary', 'TimelinePrimary']),
    ('Time is a window you drag; writes live in an agent workspace', ['TimelineWindow', 'RailGraph']),
    ('The shell: a left rail, collapsible — or Shield’s top bar from Settings', ['RailTimeline', 'TopbarGraph']),
    ('The top bar carries every destination too', ['TopbarTimeline', 'TopbarSessions']),
    ('Sign in', ['SignIn', 'SignInCreate']),
    ('Recall', ['RecallHybrid', 'RecallContext']),
    ('Review', ['ReviewDrawer', 'ReviewConfirm']),
    ('Inspector: verify and act', ['InspectorVerify', 'InspectorExtract']),
    ('Inspector: a write says what it will do first', ['InspectorSupersede', 'InspectorForget']),
    ('Files, and what Integrity can check', ['InspectorFiles', 'IntegrityServer']),
    ('Integrity', ['IntegrityCheckpoints', 'IntegrityLinks']),
    ('Memories', ['Memories', 'MemoriesEmpty']),
    ('Entities and Sessions', ['Entities', 'Sessions']),
    ('Agents and Operations', ['Agents', 'Operations']),
    ('Settings', ['SettingsLayout', 'SettingsInference']),
    ('Settings: what the profile is, and who you are', ['SettingsEmbeddings', 'SettingsAccount']),
    ('Settings: developer tools, and the API being down', ['SettingsDeveloper', 'Unavailable']),
    ('Everything but the two lenses is a drawer or a dialog, opened from where it belongs', ['DrawerTimelineSessions', 'DrawerSessionFromLens']),
    ('…including from an entity in the graph', ['DrawerEntityFromGraph']),
    ('Inspector actions: link an entity, mark a contradiction', ['InspectorLink', 'InspectorContradict']),
    ('Review: PARA, tasks, and a read-only queue', ['ReviewPara', 'ReviewTasks']),
    ('Review (continued) and the Sessions tabs', ['ReviewReadonly', 'SessionsMemories']),
    ('Sessions: decision trace and kernel intents', ['SessionsTrace', 'SessionsKernel']),
    ('Agents: pairing a device', ['AgentsPair', 'AgentsPaired']),
    ('Account: signed in, and the ways sign-in fails', ['SettingsAccountSignedIn', 'SignInError']),
    ('Sign-in: waiting for approval, and an expired session', ['SignInPending', 'SignInExpired']),
    ('Integrity: new checkpoint, and rebuild asks first', ['IntegrityCheckpointNew', 'IntegrityConfirmRebuild']),
    ('Operations readiness, and Recall results and errors', ['OperationsReadiness', 'RecallLexical']),
    ('Recall refused, and a session selected on the timeline', ['RecallError', 'TimelineSessionSelected']),
    ('Inspector, every tab', ['InspectorProvenance', 'InspectorNeighbors']),
    ('Inspector, every tab (continued)', ['InspectorContradictions', 'InspectorTelemetry']),
    ('Writing a memory, and finding a path between entities', ['MemoriesNew', 'EntitiesPath']),
    ('Sessions: replay, telemetry, invocations', ['SessionsReplay', 'SessionsTelemetry']),
    ('Sessions (continued), and the Top bar chosen in Settings', ['SessionsInvocations', 'SettingsLayoutTop']),
    ('Empty states: nothing in the workspace, nothing placed in time, nothing recalled', ['GraphEmpty', 'TimelineEmpty']),
    ('Recall with no results, and the tablet layout (1024)', ['RecallEmpty', 'TabletGraph']),
    ('Tablet (1024 and 820)', ['TabletTimeline', 'TabletMemories']),
    ('Tablet settings, and phone sign-in', ['TabletSettings', 'PhoneSignIn']),
    ('Phone: Recall, Review, and the graph legend', ['PhoneRecall', 'PhoneReview', 'PhoneGraphLegend']),
    ('Phone: Graph and Timeline, and the sheets that sit over them', ['PhoneGraphPrimary', 'PhoneTimeline', 'PhoneFilters', 'PhoneTime', 'PhoneMore', 'PhoneInspector', 'PhoneGraph2D']),
    ('Phone: pages', ['PhoneMemories', 'PhoneSessions', 'PhoneEntities', 'PhoneOperations', 'PhoneAgents', 'PhoneSettings']),
]
PLANNED_ROWS = [
    ('PLANNED — the agent runtime lives on the timeline; connectors and workers on Operations', ['PlannedRuntimeTimeline', 'PlannedRuntimes']),
    ('PLANNED — workers and connectors', ['PlannedWorkers', 'PlannedConnectors']),
    ('PLANNED — API tokens, and the profile’s configuration', ['PlannedTokens', 'PlannedProfile']),
    ('PLANNED — export the window; end a session', ['PlannedExportWindow', 'PlannedEndSession']),
    ('PLANNED — import', ['PlannedImport']),
    ('PLANNED — account recovery (the server side already exists)', ['PlannedResetRequest', 'PlannedResetConfirm']),
    ('PLANNED — approvals, and the trust vault', ['PlannedApprovals', 'PlannedVault']),
    ('PLANNED — attach a file, verify a link', ['PlannedAttach', 'PlannedLinkVerify']),
    ('PLANNED — anchor a session root, back up the store', ['PlannedAnchor', 'PlannedBackup']),
]

# ---- the console's real stylesheet, viewport units mapped to the board's own size
css = (SRC / 'tokens.css').read_text() + '\n' + (SRC / 'console.css').read_text().replace("@import './tokens.css';", '')
css = css.replace('100dvh', 'var(--board-h)').replace('100vh', 'var(--board-h)').replace('100vw', 'var(--board-w)')
assert '{{' not in css and '}}' not in css
FONTS = 'https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700&family=Barlow+Condensed:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap'


class Check(HTMLParser):
    VOID = {'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr'}
    def __init__(s): super().__init__(); s.stack = []; s.errors = []; s.ids = set()
    def handle_starttag(s, tag, attrs):
        for k, v in attrs:
            if k == 'id':
                if v in s.ids: s.errors.append('duplicate id ' + v)
                s.ids.add(v)
        if tag not in s.VOID: s.stack.append(tag)
    def handle_startendtag(s, tag, attrs): pass
    def handle_endtag(s, tag):
        if tag in s.VOID: return
        if not s.stack or s.stack[-1] != tag: s.errors.append(f'mismatched </{tag}> (open: {s.stack[-3:]})')
        else: s.stack.pop()


def clean(markup, image_key):
    m = markup
    m = m.replace('src="/cortex-mark.png"', f'src="{MARK}"')
    m = re.sub(r'<button[^>]*>(?:(?!</button>).)*Connect to local Cortex</button>', '', m, flags=re.S)
    def canvas_to_img(match):
        tag = match.group(0)
        w = re.search(r'width="(\d+)"', tag).group(1); h = re.search(r'height="(\d+)"', tag).group(1)
        return f'<img src="{CANVAS_IMAGES[image_key]}" alt="" style="width: {w}px; height: {h}px; display: block">'
    m = re.sub(r'<canvas[^>]*></canvas>', canvas_to_img, m)
    assert '<canvas' not in m
    m = m.replace('{{', '&#123;&#123;').replace('}}', '&#125;&#125;').replace('\x00', '|')
    return m


def build(b):
    d = json.loads((S / 'boards-src' / f"{b['cap']}.json").read_text())
    w, h = d['w'], MEASURED.get(b['stem'], d['h'])
    image_key = d.get('base', b['cap'])
    body = clean(d['html'], image_key)
    chk = Check(); chk.feed(body)
    assert not chk.errors and not chk.stack, (b['stem'], chk.errors, chk.stack)
    assert 'Connect to local' not in body and 'cortex-mark.png' not in body
    doc = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{htmllib.escape(b['title'])}</title>
<script src="./support.js"></script>
</head>
<body>
<x-dc>
<helmet>
<link rel="stylesheet" href="{FONTS}">
<style>
{css}
</style>
</helmet>
<!-- {'A design for something not built yet, composed from the console’s own components.' if b['status'] == 'planned' else 'A snapshot of the implemented console (dev fixture data), so this board cannot drift from what is built.'} -->
<div style="--board-w: {w}px; --board-h: {h}px; width: {w}px; height: {h}px; position: relative; overflow: hidden; transform: translateZ(0)">
{body}
</div>
</x-dc>
<script type="text/x-dc" data-dc-script data-props='{{"$preview":{{"width":{w},"height":{h}}}}}'>
class Component extends DCLogic {{
  renderVals() {{
    return {{}};
  }}
}}
</script>
</body>
</html>
'''
    (OUT / f"{b['stem']}.dc.html").write_text(doc)
    return w, h


# ---- round-1 boards: swap the old inline glyph for the complete brain mark
def refresh_round1(name):
    s = (S / 'cortex-canvas' / 'project' / name).read_text()
    def swap(m):
        size = 40 if m.group(2) == '52' else 26
        return m.group(1) + f'<img src="{MARK}" alt="" style="width: {size}px; height: {size}px; object-fit: contain; display: block">' + '</div>'
    new, n = re.subn(r'(<div style="width: (52|34)px; height: \2px; border: 1px solid \{\{accent\}\}[^"]*">)(?:(?!</div>).)*</div>', swap, s, flags=re.S)
    return new, n


index = json.loads((S / 'canvas-live' / 'project' / 'canvas.json').read_text())
changed_round1 = {}
for name in ['Main.dc.html', 'Timeline.dc.html', 'Recall.dc.html', 'Review.dc.html', 'Integrity.dc.html', 'Mobile.dc.html']:
    new, n = refresh_round1(name)
    if n:
        (OUT / name).write_text(new); changed_round1[name] = n

index['notes']['rd1'] = {'x': 3040, 'y': 0, 'w': 560, 'fill': 'gray', 'text': 'Round 1: the original design, drawn before the console was built. It is the Top bar layout. The boards from here down to the Planned section are the console as built; the Planned section is designed but not built.'}

sizes = {}
def lay(rows, y, tag):
    for n, (title, stems) in enumerate(rows):
        for st in stems: sizes[st] = build(B[st])
        row_h = max(sizes[s][1] for s in stems)
        index['notes'][f'{tag}{n+1}'] = {'x': 0, 'y': y - 280, 'text': title, 'kind': 'title1', 'maxW': 2960}
        step = 1520 if len(stems) <= 2 else 480
        for i, st in enumerate(stems):
            w, h = sizes[st]
            key = f'{st}.dc.html'
            index['boards'][key] = {'x': i * step, 'y': y, 'w': w, 'h': h, 'title': B[st]['title']}
            if key not in index['order']: index['order'].append(key)
        y += row_h + 340
    return y

y = lay(ROWS, 5900, 'b')
index['notes']['pl0'] = {'x': 0, 'y': y - 560, 'w': 640, 'fill': 'orange', 'text': 'PLANNED — everything below is designed but not built. Each board is composed from components the console already has, carries a Planned banner in the board itself, and names the route it needs. The contracts quote the backend’s real behaviour.'}
y = lay(PLANNED_ROWS, y, 'p')
(OUT / 'canvas.json').write_text(json.dumps(index, indent=2, ensure_ascii=False))

# ---- DESIGN.md: the same table, for whoever applies the boards
lines = ['# Design map', '',
         'Generated from the table that builds the Claude Design canvas **“Cortex UI — Graph-First Redesign”**; do not edit by hand.',
         'Every board is either **built** (a snapshot of the running console, taken with the dev fixture) or **planned**',
         '(designed from the console’s own components, not built, with a banner in the board naming what it needs).', '',
         'Round 1 (the original top-bar design: Main, Timeline, Recall, Review, Integrity, Inspector, Tokens, Mobile) is kept on the canvas as',
         'the *Top bar* layout option.', '',
         '## Built', '', '| Board | Source | Notes |', '|---|---|---|']
for st, b in B.items():
    if b['status'] == 'built':
        lines.append(f"| {b['title']} | `{b['source']}` | {b['note']} |")
lines += ['', '## Planned — designed, not built', '',
          '| Board | Lands in | What it needs |', '|---|---|---|']
for st, b in B.items():
    if b['status'] == 'planned':
        lines.append(f"| {b['title'].replace('PLANNED — ', '')} | `{b['source']}` | {b['note']} |")
lines += ['', '### Rules the planned designs follow', '',
          '- **No path comes from the browser.** Backup destination, vault directory, DAG location and the anchor service are server configuration; the browser sends an id or a hash.',
          '- **Outward actions are confirmed and named.** Anchoring says what is sent, to whom, and that it cannot be withdrawn; it is disabled, with the reason, when the profile has no anchor service.',
          '- **Results are worded as what they are.** A backup check shows the copy is complete, not that it will restore elsewhere; a link check is byte lineage only; a vault lookup does not verify memories.',
          '- **A failure is a different thing from “not found”.** Unavailable delivery, an unreadable vault and a missing node each say so.', '',
          '### Decisions made while filling the gaps', '',
          '- The scope picker offers **Primary profile · all memories · read only** explicitly. It is never chosen automatically, and it is the only way to see memories with no agent namespace.',
          '- On a phone, Memories rows are cards and Sessions shows the list or the detail, not both.',
          '- Timeline date labels thin themselves so neighbours stay at least 56px apart.', '']

lines += ['', '## Information architecture', '',
          'Graph and Timeline are the two ways to work; they are the only destinations. Everything else opens **over** the lens it was opened from, as a drawer or a dialog, and the lens stays mounted underneath (camera, window and selection are kept).', '',
          '| Tool | Surface | Opened from |', '|---|---|---|',
          '| Memories | drawer (wide) | the Memories count in the facet rail; Tools strip; `#memories` |',
          '| Entities | drawer (wide) | the Entities count; an entity in the inspector (“Neighbours and paths”, aimed at it) |',
          '| Sessions | drawer (wide) | the Sessions count; a session in the inspector (“Exchanges, replay, telemetry”, aimed at it) |',
          '| Operations | drawer | the connection chip at the foot of the rail |',
          '| Agents | drawer | “Agents and devices”, under the scope picker |',
          '| Settings | drawer | Tools strip |',
          '| Recall, Review, Integrity | dialog / drawer | `⌘K`; Tools strip; the workspace summary in the inspector |', '',
          'The route keeps the lens under a drawer: `#timeline/sessions`. Esc, the scrim and the close button return to the lens. On a phone a drawer is a full-screen sheet and the tab bar is unchanged.', '',
          '## Graph lens: the spec to implement from', '',
          '| Behaviour | Rule |', '|---|---|',
          '| Default view | 3D. 2D is a toggle in the bar; the choice persists (`graphMode`). Without WebGL the lens shows 2D and says why. |',
          '| Nodes | Cubes (3D) and squares (2D). One node per lattice cell; priority is degree, then id; a node near a boundary keeps its cell (hysteresis 0.62). |',
          '| Snap to grid | A button in the bar and a Settings checkbox (`graphSnap`, default on). Off: nodes stay where the force layout leaves them; the grid stays. |',
          '| Grid | Faint, in both views. 3D: a true lattice through the volume plus a brighter bounding box. 2D: a square grid. Both coarsen by powers of two so lines stay ≥ 14px (3D) or ≥ 16px (2D) apart. |',
          '| Framing | 3D looks along the cloud’s thinnest axis (PCA), with a tilt, at the nearest distance that holds every cube in the real frustum (`framing.ts`). Layout changes re-frame until the person moves the camera; Fit re-arms it. 2D does the same with zoom-to-fit. |',
          '| Resolution | A node is never smaller than 5px (3D) / 3.5px (2D). Arrowheads ≥ 10px, selected-edge bar ≥ 2px. Overlapping labels are dropped, selected and hovered first. Zoom is bounded: near stop 16 units, far stop 2.5× the framing distance. |',
          '| Mouse | Click a node or a line (6px) to select; click empty space to clear; drag empty space to orbit, right-drag to pan, wheel to zoom toward the pointer. Drag a cube to pin it; double-click to unpin. |',
          '| Keyboard | Focus the canvas (Tab): arrows orbit, shift+arrows pan, + and − zoom, F or 0 frame everything, Esc clears the selection. |',
          '| Edges | Relation (accent, arrow subject→object), contradiction (dashed, review colour), similarity (dotted, anchored colour), structure (grey: contains, prompt, response, context, Merkle root). Each group, structure type and relation predicate has a switch. |',
          '| Honesty | Counts say they are for the sample. A hidden selection is announced. Pins and positions are view state; nothing is written to the store. |', '',
          '## Implementing from this design', '',
          'The boards are snapshots of the running console in `viewer/`, so each “built” board names the files that produce it.',
          'To work on one: `cd viewer && npm install && npm run dev`, seed with `python scripts/dev_seed_console.py`, and compare against the board.',
          'Gates before a change is done: `npx tsc -b`, `npx oxlint src`, `npx vitest run` (pure logic: `model`, `gridSnap`, `framing`, `graphStyle`, `settings`).',
          'Not covered by checked-in tests: the WebGL engine itself and the browser flows; both were verified by hand in Chromium (software WebGL).', '']
REPO_DESIGN.write_text('\n'.join(lines))

print('boards built', len(sizes), '| round-1 refreshed', changed_round1, '| canvas boards', len(index['boards']), '| last y', y)
